In [1]:
import pandas as pd

In [2]:
FEMA = pd.read_csv('https://www.fema.gov/api/open/v1/FemaWebDisasterDeclarations.csv')

In [3]:
FEMA.head()

,disasterNumber,declarationDate,disasterName,incidentBeginDate,incidentEndDate,declarationType,stateCode,stateName,incidentType,entryDate,updateDate,closeoutDate,region,ihProgramDeclared,iaProgramDeclared,paProgramDeclared,hmProgramDeclared,id,hash,lastRefresh
0,4694,2023-03-15T00:00:00.000Z,SEVERE WINTER STORM AND SNOWSTORM,2022-12-23T00:00:00.000Z,2022-12-28T00:00:00.000Z,Major Disaster,NY,New York,Snowstorm,2023-03-16T00:00:00.000Z,2023-03-16T00:00:00.000Z,NaN,2,1.0,0.0,1.0,1.0,10919b86-0901-4ebc-8004-b199dcd25221,72f583618efcc7306eabe38c0492524ad33ec0f6,2023-03-18T13:22:06.532Z
1,4693,2023-03-15T00:00:00.000Z,SEVERE STORM AND FLOODING,2022-12-22T00:00:00.000Z,2022-12-25T00:00:00.000Z,Major Disaster,NH,New Hampshire,Severe Storm,2023-03-15T00:00:00.000Z,2023-03-15T00:00:00.000Z,NaN,1,0.0,0.0,1.0,1.0,0b6abb1a-e846-47aa-9739-04b35bb1a158,00c2550e7102e7a7238d5c6279f75d8176a5e688,2023-03-18T13:22:06.532Z
2,3592,2023-03-10T00:00:00.000Z,"SEVERE WINTER STORMS, FLOODING, LANDSLIDES, AN...",2023-03-09T00:00:00.000Z,NaN,Emergency,CA,California,Flood,2023-03-10T00:00:00.000Z,2023-03-16T00:00:00.000Z,NaN,9,0.0,0.0,1.0,0.0,29951a6b-6b69-471e-8141-7e0c10a874f6,379963769a581940659f2f091b4c45bb9fca2995,2023-03-18T13:22:06.532Z
3,4691,2023-03-08T00:00:00.000Z,SEVERE WINTER STORM,2022-12-22T00:00:00.000Z,2022-12-27T00:00:00.000Z,Major Disaster,TN,Tennessee,Winter Storm,2023-03-08T00:00:00.000Z,2023-03-08T00:00:00.000Z,NaN,4,0.0,0.0,1.0,1.0,68c24ed2-3f35-49f2-9e58-572d2094d77c,2d3e9d876f4237843ff258bdc5ec57f7736b157c,2023-03-18T13:22:06.532Z
4,4692,2023-03-08T00:00:00.000Z,EARTHQUAKE,2022-12-20T00:00:00.000Z,2023-01-01T00:00:00.000Z,Major Disaster,CA,California,Earthquake,2023-03-08T00:00:00.000Z,2023-03-08T00:00:00.000Z,NaN,9,0.0,0.0,1.0,1.0,5cbc8c79-d21c-46da-aa48-2dae464f294e,9cfa08515478fdc74f7ae329b2a38f3650599043,2023-03-18T13:22:06.532Z

In [4]:
FEMA.shape

(4752, 20)

In [5]:
FEMA.drop(['declarationDate', 'declarationType', 'entryDate', 'updateDate', 'closeoutDate', 'region', 'ihProgramDeclared', 'iaProgramDeclared', 'paProgramDeclared', 'hmProgramDeclared', 'id', 'hash', 'lastRefresh'], axis=1, inplace=True)

In [6]:
FEMA.head()

,disasterNumber,disasterName,incidentBeginDate,incidentEndDate,stateCode,stateName,incidentType
0,4694,SEVERE WINTER STORM AND SNOWSTORM,2022-12-23T00:00:00.000Z,2022-12-28T00:00:00.000Z,NY,New York,Snowstorm
1,4693,SEVERE STORM AND FLOODING,2022-12-22T00:00:00.000Z,2022-12-25T00:00:00.000Z,NH,New Hampshire,Severe Storm
2,3592,"SEVERE WINTER STORMS, FLOODING, LANDSLIDES, AN...",2023-03-09T00:00:00.000Z,NaN,CA,California,Flood
3,4691,SEVERE WINTER STORM,2022-12-22T00:00:00.000Z,2022-12-27T00:00:00.000Z,TN,Tennessee,Winter Storm
4,4692,EARTHQUAKE,2022-12-20T00:00:00.000Z,2023-01-01T00:00:00.000Z,CA,California,Earthquake

In [7]:
FEMA.shape

(4752, 7)

In [8]:
FEMA = FEMA.loc[FEMA['disasterName'] != 'COVID-19']

In [9]:
FEMA.shape

(4644, 7)

In [10]:
FEMA.head(426)

,disasterNumber,disasterName,incidentBeginDate,incidentEndDate,stateCode,stateName,incidentType
0,4694,SEVERE WINTER STORM AND SNOWSTORM,2022-12-23T00:00:00.000Z,2022-12-28T00:00:00.000Z,NY,New York,Snowstorm
1,4693,SEVERE STORM AND FLOODING,2022-12-22T00:00:00.000Z,2022-12-25T00:00:00.000Z,NH,New Hampshire,Severe Storm
2,3592,"SEVERE WINTER STORMS, FLOODING, LANDSLIDES, AN...",2023-03-09T00:00:00.000Z,NaN,CA,California,Flood
3,4691,SEVERE WINTER STORM,2022-12-22T00:00:00.000Z,2022-12-27T00:00:00.000Z,TN,Tennessee,Winter Storm
4,4692,EARTHQUAKE,2022-12-20T00:00:00.000Z,2023-01-01T00:00:00.000Z,CA,California,Earthquake
...,...,...,...,...,...,...,...
529,4478,"SEVERE STORMS, TORNADOES, STRAIGHT-LINE WINDS,...",2020-01-10T00:00:00.000Z,2020-01-11T00:00:00.000Z,MS,Mississippi,Severe Storm
530,4477,SEVERE WINTER STORM AND FLOODING,2020-01-10T00:00:00.000Z,2020-01-12T00:00:00.000Z,WI,Wisconsin,Flood
531,5306,412 FIRE COMPLEX,2020-03-07T00:00:00.000Z,2020-03-11T00:00:00.000Z,OK,Oklahoma,Fire
532,4476,"SEVERE STORMS, TORNADOES, STRAIGHT-LINE WINDS,...",2020-03-03T00:00:00.000Z,2020-03-03T00:00:00.000Z,TN,Tennessee,Tornado
533,4475,FLOODING,2019-10-09T00:00:00.000Z,2019-10-26T00:00:00.000Z,ND,North Dakota,Flood

In [16]:
print(type(FEMA.incidentBeginDate[1]))

<class 'str'>

In [19]:
FEMA['beginYear'] = FEMA.incidentBeginDate.str[0:4]
FEMA.head()

,disasterNumber,disasterName,incidentBeginDate,incidentEndDate,stateCode,stateName,incidentType,beginYear
0,4694,SEVERE WINTER STORM AND SNOWSTORM,2022-12-23T00:00:00.000Z,2022-12-28T00:00:00.000Z,NY,New York,Snowstorm,2022
1,4693,SEVERE STORM AND FLOODING,2022-12-22T00:00:00.000Z,2022-12-25T00:00:00.000Z,NH,New Hampshire,Severe Storm,2022
2,3592,"SEVERE WINTER STORMS, FLOODING, LANDSLIDES, AN...",2023-03-09T00:00:00.000Z,NaN,CA,California,Flood,2023
3,4691,SEVERE WINTER STORM,2022-12-22T00:00:00.000Z,2022-12-27T00:00:00.000Z,TN,Tennessee,Winter Storm,2022
4,4692,EARTHQUAKE,2022-12-20T00:00:00.000Z,2023-01-01T00:00:00.000Z,CA,California,Earthquake,2022

In [71]:
FEMA.to_csv('FEMA.csv')